name: CMake
on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  PICO_SDK_REPO: https://github.com/raspberrypi/pico-sdk.git
  PICO_SDK_REF: master
  FREERTOS_KERNEL_REPO: https://github.com/FreeRTOS/FreeRTOS-Kernel.git
  FREERTOS_KERNEL_REF: main
  UNITY_REPO: https://github.com/ThrowTheSwitch/Unity.git
  UNITY_REF: master
  OPENOCD_REPO: https://github.com/openocd-org/openocd.git
  OPENOCD_REF: master
  PICO_TOOLCHAIN_REPO: https://github.com/raspberrypi/pico-sdk.git
  PICO_TOOLCHAIN_REF: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
          mkdir -p "${{ github.workspace }}"

      - uses: actions/checkout@v3
        with:
          path: ${{github.workspace}}/source

      - name: Clone Dependencies
        working-directory: ${{github.workspace}}
        run: |
          git clone --branch ${{ env.PICO_SDK_REF }} ${{ env.PICO_SDK_REPO }} pico-sdk
          git clone --branch ${{ env.FREERTOS_KERNEL_REF }} ${{ env.FREERTOS_KERNEL_REPO }} FreeRTOS-Kernel
          git clone --branch ${{ env.UNITY_REF }} ${{ env.UNITY_REPO }} Unity
          git clone --branch ${{ env.OPENOCD_REF }} ${{ env.OPENOCD_REPO }} openocd
          git clone --branch ${{ env.PICO_TOOLCHAIN_REF }} ${{ env.PICO_TOOLCHAIN_REPO }} pico-toolchain

      - name: Create Build Environment
        working-directory: ${{github.workspace}}
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}
        run: |
          cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DPICO_SDK_PATH=${{github.workspace}}/pico-sdk \
            -DFREERTOS_KERNEL_PATH=${{github.workspace}}/FreeRTOS-Kernel \
            -DUNITY_PATH=${{github.workspace}}/Unity \
            -DOPENOCD_PATH=${{github.workspace}}/openocd \
            -B ./build ./source

      - name: Build
        working-directory: ${{github.workspace}}
        shell: bash
        run: cmake --build ./build --config $BUILD_TYPE --parallel $(nproc)

      - name: Flash
        working-directory: ${{github.workspace}}/build/test
        shell: bash
        run: |
          ${{github.workspace}}/openocd/src/openocd \
            -f ${{github.workspace}}/openocd/tcl/interface/cmsis-dap.cfg \
            -f ${{github.workspace}}/openocd/tcl/target/rp2040.cfg \
            -c 'adapter speed 5000; program "mytest.elf" verify reset exit'

      - name: Test
        working-directory: ${{github.workspace}}
        shell: bash
        run: python3 ${{github.workspace}}/Unity/unity_checker.py

